# ==========================================================
# OLLAMA SERVICE
# VentureIQ
# ==========================================================


import requests


# ==========================================================
# OLLAMA CONFIGURATION
# ==========================================================


OLLAMA_URL = (

    "http://localhost:11434/api/generate"

)


OLLAMA_MODEL = (

    "qwen2.5:3b"

)


# ==========================================================
# GENERATE AI RESPONSE
# ==========================================================


def generate_ai_response(

    context: str

) -> dict:


    """

    Generates a natural-language response using Ollama.

    Used for:

    - Investment Memo
    - AI-generated startup analysis
    - Explanation of ML outputs
    - Startup intelligence reports

    The ML predictions and feature-engineered values
    are already present in the CSV data.

    Ollama acts only as the natural-language
    explanation layer.

    """


    # ------------------------------------------------------
    # INVESTMENT MEMO PROMPT
    # ------------------------------------------------------


    prompt = f"""

You are VentureIQ, an AI-powered startup intelligence assistant.

You are generating an investment memo based ONLY on the
startup data provided below.

==========================================================
STARTUP DATA
==========================================================

{context}

==========================================================
INSTRUCTIONS
==========================================================

1. Use ONLY the startup data provided above.

2. Do not invent financial numbers.

3. Do not invent investors.

4. Do not invent funding amounts.

5. Do not invent market size.

6. Do not invent predictions.

7. Do not recalculate machine-learning predictions.

8. The numerical ML outputs and feature-engineered values
   already exist in the provided startup data.

9. Your role is only to explain the available data
   in clear natural language.

10. If a value is missing, clearly state:

    "Not available in the provided startup data."

11. Do not assume that every startup has the same risks.

12. Explain risks using the actual startup data.

13. Explain strengths using the actual startup data.

14. Keep the analysis objective and investor-focused.

15. Do not make a guaranteed investment recommendation.

16. Clearly distinguish between:

    - Data-backed metrics
    - Model predictions
    - Analytical interpretation

==========================================================
GENERATE THE INVESTMENT MEMO USING THESE SECTIONS
==========================================================

Investment Overview

Startup Summary

Investment Thesis

Market Opportunity

Growth Potential

Financial Health

Competitive Position

Funding Readiness

Key Risks

Red Flags

Investor Fit

Exit Potential

Overall Investment Recommendation

==========================================================
OUTPUT FORMAT
==========================================================

Use clear section headings.

Use concise paragraphs.

Use bullet points where useful.

Return only the investment memo.

==========================================================

INVESTMENT MEMO:

"""


    # ------------------------------------------------------
    # OLLAMA REQUEST
    # ------------------------------------------------------


    try:


        response = requests.post(

            OLLAMA_URL,

            json={

                "model": OLLAMA_MODEL,

                "prompt": prompt,

                "stream": False

            },

            timeout=180

        )


        response.raise_for_status()


        result = response.json()


        return {

            "status": "success",

            "response": result.get(

                "response",

                "No response generated by Ollama."

            )

        }


    except requests.exceptions.RequestException as error:


        return {

            "status": "error",

            "response": (

                f"Ollama request failed: {error}"

            )

        }


    except Exception as error:


        return {

            "status": "error",

            "response": (

                f"Unexpected Ollama error: {error}"

            )

        }


# ==========================================================
# GENERATE NATURAL LANGUAGE ANSWER
# ==========================================================


def generate_natural_language_qa(

    startup_name: str,

    question: str,

    startup_context: dict,

    dataset_type: str = "new"

) -> str:


    """

    Generates a natural-language answer using Ollama.

    Used for:

    - Normal startup Q&A
    - Advantages
    - Disadvantages
    - Risks
    - Investment-related questions

    """


    # ------------------------------------------------------
    # CONVERT CONTEXT TO TEXT
    # ------------------------------------------------------


    context_text = "\n".join(

        [

            f"{key}: {value}"

            for key, value

            in startup_context.items()

        ]

    )


    # ------------------------------------------------------
    # PROMPT
    # ------------------------------------------------------


    prompt = f"""

You are VentureIQ, an AI-powered startup intelligence assistant.

You are answering a question about the startup:

Startup Name:

{startup_name}


Dataset Type:

{dataset_type}


STARTUP DATA:

{context_text}


USER QUESTION:

{question}


INSTRUCTIONS:

1. Answer the user's question directly.

2. Use ONLY the startup data provided above.

3. Do not invent financial numbers, investors,
   funding, or predictions.

4. If a value is not available, clearly say:

   "Not available in the provided startup data."

5. Give a clear and structured answer.

6. If the question asks about risk, explain the specific risks
   using the startup's actual data.

7. If the question asks about advantages or strengths,
   explain the startup's actual advantages.

8. If the question asks about disadvantages, weaknesses,
   or why the startup is risky, explain the actual weaknesses
   and risks based on the startup data.

9. Do not give generic startup risks unless they are relevant
   to the provided startup data.

10. Do not assume that every startup has the same risks.

11. Keep the answer concise but informative.

12. Use Markdown formatting where useful.

ANSWER:

"""


    # ------------------------------------------------------
    # OLLAMA REQUEST
    # ------------------------------------------------------


    try:


        response = requests.post(

            OLLAMA_URL,

            json={

                "model": OLLAMA_MODEL,

                "prompt": prompt,

                "stream": False

            },

            timeout=180

        )


        response.raise_for_status()


        result = response.json()


        return result.get(

            "response",

            "No response generated by Ollama."

        )


    except requests.exceptions.RequestException as error:


        return (

            f"Ollama request failed: {error}"

        )


    except Exception as error:


        return (

            f"Unexpected Ollama error: {error}"

        )


# ==========================================================
# GENERATE VC COPILOT RESPONSE
# ==========================================================


def generate_vc_copilot_response(

    startup_name: str,

    question: str,

    investor_context: dict,

    dataset_type: str = "new"

) -> str:


    """

    Generates an investor-oriented answer for VC Copilot.

    The model uses only the structured investor context
    created from the selected CSV dataset.

    """


    # ------------------------------------------------------
    # CONVERT CONTEXT TO TEXT
    # ------------------------------------------------------


    context_sections = []


    for section, section_data in investor_context.items():


        if isinstance(

            section_data,

            dict

        ):


            section_text = "\n".join(

                [

                    f"{key}: {value}"

                    for key, value

                    in section_data.items()

                ]

            )


            context_sections.append(

                f"{section.upper()}:\n"

                f"{section_text}"

            )


    context_text = "\n\n".join(

        context_sections

    )


    # ------------------------------------------------------
    # PROMPT
    # ------------------------------------------------------


    prompt = f"""

You are VentureIQ VC Copilot.

You are assisting a venture capital investor.

==========================================================
STARTUP
==========================================================

{startup_name}


==========================================================
DATASET TYPE
==========================================================

{dataset_type}


==========================================================
INVESTOR QUESTION
==========================================================

{question}


==========================================================
INVESTOR-RELEVANT STARTUP DATA
==========================================================

{context_text}


==========================================================
YOUR ROLE
==========================================================

Analyze the startup using ONLY the provided startup data.

The startup data contains:

- Historical metrics
- Financial metrics
- Growth metrics
- Feature-engineered scores
- ML predictions
- ML probabilities
- Risk indicators
- Investment indicators

You are an explanation and decision-support layer.

You must NOT invent data.

You must NOT create new predictions.

You must NOT guarantee investment returns.

You must NOT make claims that are unsupported by the provided data.


==========================================================
ANSWER REQUIREMENTS
==========================================================

1. Answer the investor's question directly.

2. Use the actual metrics and predictions available
   in the startup data.

3. Explain the main factors supporting the investment case.

4. Explain the main risks and weaknesses.

5. Clearly distinguish between:

   - Observed metrics
   - ML predictions
   - Analytical interpretation

6. If a value is unavailable, say:

   "Not available in the provided startup data."

7. Do not use generic startup risks unless they are relevant
   to the provided startup data.

8. Do not assume that a high score automatically means
   the startup is a good investment.

9. Do not assume that a prediction is a guarantee.

10. Provide a balanced investor-oriented conclusion.


==========================================================
RESPONSE FORMAT
==========================================================

Direct Investor View

Supporting Evidence

Growth Case

Risk Considerations

Investment Consideration


==========================================================

VC COPILOT ANSWER:

"""


    # ------------------------------------------------------
    # OLLAMA REQUEST
    # ------------------------------------------------------


    try:


        response = requests.post(

            OLLAMA_URL,

            json={

                "model": OLLAMA_MODEL,

                "prompt": prompt,

                "stream": False

            },

            timeout=180

        )


        response.raise_for_status()


        result = response.json()


        return result.get(

            "response",

            "No response generated by Ollama."

        )


    except requests.exceptions.RequestException as error:


        return (

            f"Ollama request failed: {error}"

        )


    except Exception as error:


        return (

            f"Unexpected Ollama error: {error}"

        )